#!/bin/bash

# Copyright 2019 Dmitri Rubinstein
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eo pipefail

export LC_ALL=C
unset CDPATH

THIS_DIR=$( (cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P) )

# shellcheck source=kube-shlib.sh
source "$THIS_DIR/kube-shlib.sh"

define-kubectl-funcs

if [[ $# -eq 0 || "$1" = "--help" || "$1" = "-h" ]]; then
    echo "Usage: $0 kubernetes-config-file"
    echo
    echo "Merges kubernetes-config-file into ~/.kube/config configuration file"
    echo
    exit 0
fi

if [[ ! -e ~/.kube/config ]]; then
    fatal "File ~/.kube/config not found"
fi

if [[ ! -e "$1" ]]; then
    fatal "File $1 not found"
fi

TMPF=$(mktemp)
trap '{ rm -f "$TMPF"; }' EXIT
KUBECONFIG=~/.kube/config:"$1" run-kubectl-ctx config view --flatten > "$TMPF"
mv "$TMPF" ~/.kube/config
