#!/bin/bash

# Copyright 2019 Dmitri Rubinstein
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eo pipefail

export LC_ALL=C
unset CDPATH

THIS_DIR=$( (cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P))

# shellcheck source=kube-shlib.sh
source "$THIS_DIR/kube-shlib.sh"

define-kubectl-funcs

# shellcheck disable=SC2016
TMPL='{{"NAMESPACE,POD NAME,USED NVIDIA GPUs\n"}}{{range .items}}{{if (eq .status.phase "Running")}}{{$pns:=.metadata.namespace}}{{$pname:=.metadata.name}}{{range .spec.containers}}{{ with .resources.requests }}{{$gpus:=(index . "nvidia.com/gpu")}}{{if $gpus}}{{$pns}}{{","}}{{$pname}}{{","}}{{$gpus}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}{{end}}'

if command -v column &>/dev/null; then
    run-kubectl-ctx get pods --all-namespaces -o go-template --template "$TMPL" | column -t -s ','
else
    TMPL="${TMPL//,/\\t}"
    run-kubectl-ctx get pods --all-namespaces -o go-template --template "$TMPL"
fi
